-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL

CREATE TABLE "calendar_date" (
  "date" date PRIMARY KEY,
  "month" date,
  "quarter" varchar,
  "year" int
);

CREATE TABLE "region" (
  "region_id" int PRIMARY KEY,
  "region_name" varchar
);

CREATE TABLE "solar_system" (
  "solar_system_id" int PRIMARY KEY,
  "solar_system_name" varchar,
  "region_id" int NOT NULL,
  "security_band" varchar
);

CREATE TABLE "item_type" (
  "type_id" int PRIMARY KEY,
  "type_name" varchar,
  "group_name" varchar,
  "category_name" varchar,
  "mean_isk_value" decimal
);

CREATE TABLE "alliance" (
  "alliance_id" int PRIMARY KEY,
  "alliance_name" varchar,
  "ticker" varchar,
  "date_founded" timestamp,
  "executor_corporation_id" int
);

CREATE TABLE "corporation" (
  "corporation_id" int PRIMARY KEY,
  "corporation_name" varchar,
  "ticker" varchar,
  "alliance_id" int,
  "date_founded" timestamp,
  "member_count" int,
  "is_npc" boolean
);

CREATE TABLE "player_character" (
  "character_id" bigint PRIMARY KEY,
  "character_name" varchar,
  "signup_date" date,
  "signup_date_source" varchar,
  "gender" varchar,
  "race_id" int,
  "bloodline_id" int,
  "corporation_id" int NOT NULL,
  "security_status" decimal,
  "is_deleted" boolean
);

CREATE TABLE "killmail" (
  "killmail_id" bigint PRIMARY KEY,
  "killmail_time" timestamp,
  "kill_date" date NOT NULL,
  "solar_system_id" int NOT NULL,
  "war_id" int,
  "attacker_count" int
);

CREATE TABLE "killmail_participant" (
  "killmail_id" bigint,
  "participant_no" int,
  "role" varchar,
  "character_id" bigint,
  "corporation_id" int,
  "alliance_id" int,
  "ship_type_id" int,
  "weapon_type_id" int,
  "damage" int,
  "final_blow" boolean,
  PRIMARY KEY ("killmail_id", "participant_no")
);

CREATE TABLE "character_month_activity" (
  "character_id" bigint,
  "month" date,
  "kills" int,
  "losses" int,
  "active_days" int,
  PRIMARY KEY ("character_id", "month")
);

CREATE TABLE "source_document" (
  "source_id" int PRIMARY KEY,
  "source_name" varchar,
  "publisher" varchar,
  "url" varchar,
  "retrieved_at" timestamp,
  "sha256" varchar,
  "data_nature" varchar
);

CREATE TABLE "plan" (
  "plan_id" int PRIMARY KEY,
  "plan_name" varchar,
  "product_type" varchar,
  "billing_cycle_months" int
);

CREATE TABLE "plan_price" (
  "plan_id" int,
  "effective_date" date,
  "currency" varchar,
  "list_price" decimal,
  "sale_price" decimal,
  "source_id" int NOT NULL,
  PRIMARY KEY ("plan_id", "effective_date", "currency")
);

CREATE TABLE "market_history_daily" (
  "date" date,
  "region_id" int,
  "type_id" int,
  "average_price" decimal,
  "highest_price" decimal,
  "lowest_price" decimal,
  "volume" bigint,
  "order_count" int,
  PRIMARY KEY ("date", "region_id", "type_id")
);

CREATE TABLE "financial_metric" (
  "metric_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "period_start" date NOT NULL,
  "period_end" date,
  "granularity" varchar,
  "entity" varchar,
  "metric" varchar,
  "geography" varchar,
  "amount" decimal,
  "currency" varchar,
  "source_id" int NOT NULL
);

CREATE TABLE "economy_daily" (
  "date" date,
  "metric" varchar,
  "value" decimal,
  PRIMARY KEY ("date", "metric")
);

CREATE TABLE "steam_review" (
  "recommendation_id" bigint PRIMARY KEY,
  "steam_author_id" bigint,
  "created_date" date NOT NULL,
  "language" varchar,
  "voted_up" boolean,
  "playtime_at_review_hours" decimal,
  "steam_purchase" boolean,
  "received_for_free" boolean,
  "votes_up" int,
  "review_text" text
);

CREATE INDEX ON "killmail_participant" ("character_id", "killmail_id");

COMMENT ON TABLE "calendar_date" IS 'Generated. The glue between per-player and company-level data.';

COMMENT ON COLUMN "calendar_date"."month" IS 'first day of month, for cohorts and MAU';

COMMENT ON COLUMN "calendar_date"."quarter" IS 'e.g. 2025Q3, joins Pearl Abyss quarters';

COMMENT ON TABLE "region" IS 'From MER static_solarsystems.';

COMMENT ON TABLE "solar_system" IS 'From MER static_solarsystems.';

COMMENT ON COLUMN "solar_system"."security_band" IS 'High Sec / Low Sec / Null Sec / Wormhole (MER solarsystem_metagroup)';

COMMENT ON TABLE "item_type" IS 'Names, groups and categories need CCP static data (SDE via EVE Ref reference-data): NOT DOWNLOADED YET.';

COMMENT ON COLUMN "item_type"."group_name" IS 'e.g. Frigate, Battleship';

COMMENT ON COLUMN "item_type"."category_name" IS 'e.g. Ship, Module, PLEX';

COMMENT ON COLUMN "item_type"."mean_isk_value" IS 'MER static_type_values';

COMMENT ON TABLE "alliance" IS 'From character dump alliances.json.';

COMMENT ON TABLE "corporation" IS 'From character dump corporations.json.';

COMMENT ON COLUMN "corporation"."is_npc" IS 'corporation_id < 2000000 (CCP-run starter corps, incl. Doomheim)';

COMMENT ON TABLE "player_character" IS 'Customer. Built from character dump + esi_characters. Scope: characters that appear in killmails (838,881).';

COMMENT ON COLUMN "player_character"."character_id" IS 'Customer. One account can own several characters.';

COMMENT ON COLUMN "player_character"."signup_date" IS 'birthday. Dump if real (>= 2003), else ESI, else null';

COMMENT ON COLUMN "player_character"."signup_date_source" IS 'dump / esi / unknown';

COMMENT ON COLUMN "player_character"."corporation_id" IS 'current, at snapshot';

COMMENT ON COLUMN "player_character"."is_deleted" IS 'dump deleted flag, ESI 404, or corporation = Doomheim (1000001)';

COMMENT ON TABLE "killmail" IS 'UsageEvent. One ship destroyed. From EVE Ref killmails.';

COMMENT ON TABLE "killmail_participant" IS 'Victim and attackers in one table, so "was this character active?" is one lookup.';

COMMENT ON COLUMN "killmail_participant"."participant_no" IS '0 = victim, 1..n = attackers';

COMMENT ON COLUMN "killmail_participant"."role" IS 'victim / attacker';

COMMENT ON COLUMN "killmail_participant"."character_id" IS 'null for NPCs and structures';

COMMENT ON COLUMN "killmail_participant"."corporation_id" IS 'at the time of the kill';

COMMENT ON COLUMN "killmail_participant"."alliance_id" IS 'at the time of the kill';

COMMENT ON COLUMN "killmail_participant"."damage" IS 'damage_taken for victim, damage_done for attacker';

COMMENT ON TABLE "character_month_activity" IS 'Derived from killmail_participant. Feeds DAU/MAU, cohort retention and churn.';

COMMENT ON TABLE "source_document" IS 'From data/raw/sources.csv. Provenance for every figure below.';

COMMENT ON COLUMN "source_document"."data_nature" IS 'real / anonymised / synthetic';

COMMENT ON TABLE "plan" IS 'Plan. Omega periods from CCP annual accounts; packs from store pages and news.';

COMMENT ON COLUMN "plan"."plan_name" IS 'e.g. Omega 1 month, Omega 12 months, PLEX 500';

COMMENT ON COLUMN "plan"."product_type" IS 'subscription / in-game currency';

COMMENT ON COLUMN "plan"."billing_cycle_months" IS '1, 3, 6, 12, 24 (CCP accounting policy)';

COMMENT ON TABLE "plan_price" IS 'Price history. From Wayback store snapshots and CCP news articles.';

COMMENT ON COLUMN "plan_price"."sale_price" IS 'when a sale was running';

COMMENT ON TABLE "market_history_daily" IS 'From EVE Ref market history. Keep PLEX (type_id 44992) at minimum: the monetization signal for 2026.';

COMMENT ON COLUMN "market_history_daily"."average_price" IS 'ISK';

COMMENT ON TABLE "financial_metric" IS 'Long format: one reported figure per row. From CCP annual accounts and Pearl Abyss reports.';

COMMENT ON COLUMN "financial_metric"."granularity" IS 'quarter / year';

COMMENT ON COLUMN "financial_metric"."entity" IS 'CCP ehf. / Pearl Abyss (EVE IP)';

COMMENT ON COLUMN "financial_metric"."metric" IS 'total_revenue, subscription_and_ingame_revenue, marketing_expense, deferred_subscriptions, ...';

COMMENT ON COLUMN "financial_metric"."geography" IS 'North America / Europe / Asia / Other, when reported';

COMMENT ON COLUMN "financial_metric"."currency" IS 'USD (CCP) / KRW (Pearl Abyss)';

COMMENT ON TABLE "economy_daily" IS 'From MER money_supply and sinks_and_faucets_history (latest MER only: each MER holds full history).';

COMMENT ON COLUMN "economy_daily"."metric" IS 'total_isk, character_isk, isk_velocity, sink:<entry>, faucet:<entry>';

COMMENT ON TABLE "steam_review" IS 'SurveyResponse proxy. From Steam appreviews API (app 8500).';

COMMENT ON COLUMN "steam_review"."steam_author_id" IS 'Steam account, NOT linkable to a character';

COMMENT ON COLUMN "steam_review"."voted_up" IS 'recommend yes / no: the NPS proxy';

ALTER TABLE "solar_system" ADD FOREIGN KEY ("region_id") REFERENCES "region" ("region_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "corporation" ADD FOREIGN KEY ("alliance_id") REFERENCES "alliance" ("alliance_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_character" ADD FOREIGN KEY ("corporation_id") REFERENCES "corporation" ("corporation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail" ADD FOREIGN KEY ("kill_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail" ADD FOREIGN KEY ("solar_system_id") REFERENCES "solar_system" ("solar_system_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("killmail_id") REFERENCES "killmail" ("killmail_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("character_id") REFERENCES "player_character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("corporation_id") REFERENCES "corporation" ("corporation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("alliance_id") REFERENCES "alliance" ("alliance_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("ship_type_id") REFERENCES "item_type" ("type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("weapon_type_id") REFERENCES "item_type" ("type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "character_month_activity" ADD FOREIGN KEY ("character_id") REFERENCES "player_character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_price" ADD FOREIGN KEY ("plan_id") REFERENCES "plan" ("plan_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_price" ADD FOREIGN KEY ("effective_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_price" ADD FOREIGN KEY ("source_id") REFERENCES "source_document" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "market_history_daily" ADD FOREIGN KEY ("date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "market_history_daily" ADD FOREIGN KEY ("region_id") REFERENCES "region" ("region_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "market_history_daily" ADD FOREIGN KEY ("type_id") REFERENCES "item_type" ("type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "financial_metric" ADD FOREIGN KEY ("period_start") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "financial_metric" ADD FOREIGN KEY ("source_id") REFERENCES "source_document" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "economy_daily" ADD FOREIGN KEY ("date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "steam_review" ADD FOREIGN KEY ("created_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;
