-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL

CREATE TABLE "calendar_date" (
  "date" date PRIMARY KEY,
  "month" date NOT NULL,
  "quarter" varchar NOT NULL,
  "year" int NOT NULL,
  "after_sale" boolean NOT NULL
);

CREATE TABLE "region" (
  "region_id" int PRIMARY KEY,
  "region_name" varchar NOT NULL
);

CREATE TABLE "constellation" (
  "constellation_id" int PRIMARY KEY,
  "constellation_name" varchar NOT NULL,
  "region_id" int NOT NULL
);

CREATE TABLE "solar_system" (
  "solar_system_id" int PRIMARY KEY,
  "solar_system_name" varchar NOT NULL,
  "constellation_id" int NOT NULL,
  "security_status" decimal,
  "security_band" varchar
);

CREATE TABLE "item_category" (
  "category_id" int PRIMARY KEY,
  "category_name" varchar NOT NULL
);

CREATE TABLE "item_group" (
  "group_id" int PRIMARY KEY,
  "group_name" varchar NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "item_type" (
  "type_id" int PRIMARY KEY,
  "type_name" varchar NOT NULL,
  "group_id" int NOT NULL,
  "mean_isk_value" decimal,
  "alpha_can_fly" boolean
);

CREATE TABLE "alliance" (
  "alliance_id" int PRIMARY KEY,
  "alliance_name" varchar,
  "ticker" varchar,
  "date_founded" timestamp,
  "executor_corporation_id" int
);

CREATE TABLE "corporation" (
  "corporation_id" int PRIMARY KEY,
  "corporation_name" varchar,
  "ticker" varchar,
  "alliance_id" int,
  "date_founded" timestamp,
  "member_count" int,
  "is_npc" boolean
);

CREATE TABLE "player_character" (
  "character_id" bigint PRIMARY KEY,
  "character_name" varchar,
  "signup_date" date,
  "signup_date_source" varchar,
  "cohort_month" date,
  "gender" varchar,
  "race_id" int,
  "bloodline_id" int,
  "corporation_id" int NOT NULL,
  "security_status" decimal,
  "is_deleted" boolean,
  "inferred_plan" varchar,
  "first_omega_seen" date
);

CREATE TABLE "character_signup_month" (
  "month" date PRIMARY KEY,
  "first_character_id" bigint NOT NULL,
  "characters_created" int NOT NULL
);

CREATE TABLE "killmail" (
  "killmail_id" bigint PRIMARY KEY,
  "killmail_time" timestamp NOT NULL,
  "kill_date" date NOT NULL,
  "solar_system_id" int NOT NULL,
  "war_id" int,
  "battle_id" int,
  "attacker_count" int
);

CREATE TABLE "killmail_participant" (
  "killmail_id" bigint,
  "participant_no" int,
  "role" varchar NOT NULL,
  "character_id" bigint,
  "corporation_id" int,
  "alliance_id" int,
  "ship_type_id" int,
  "weapon_type_id" int,
  "damage" int,
  "final_blow" boolean,
  PRIMARY KEY ("killmail_id", "participant_no")
);

CREATE TABLE "contract" (
  "contract_id" bigint PRIMARY KEY,
  "issuer_character_id" bigint NOT NULL,
  "issuer_corporation_id" int,
  "contract_type" varchar NOT NULL,
  "date_issued" timestamp NOT NULL,
  "issued_date" date NOT NULL,
  "date_expired" timestamp,
  "price" decimal,
  "reward" decimal,
  "collateral" decimal,
  "volume" decimal,
  "region_id" int,
  "solar_system_id" int,
  "first_seen" date,
  "last_seen" date
);

CREATE TABLE "character_month_activity" (
  "character_id" bigint,
  "month" date,
  "kills" int,
  "losses" int,
  "contracts_issued" int,
  "active_days" int,
  "flew_omega_ship" boolean,
  "in_player_corporation" boolean,
  PRIMARY KEY ("character_id", "month")
);

CREATE TABLE "players_online_daily" (
  "date" date PRIMARY KEY,
  "avg_players" int,
  "peak_players" int,
  "min_players" int,
  "outage_minutes" int
);

CREATE TABLE "war" (
  "war_id" int PRIMARY KEY,
  "aggressor_corporation_id" int,
  "aggressor_alliance_id" int,
  "defender_corporation_id" int,
  "defender_alliance_id" int,
  "declared" timestamp,
  "started" timestamp,
  "finished" timestamp,
  "mutual" boolean,
  "open_for_allies" boolean,
  "aggressor_ships_killed" int,
  "defender_ships_killed" int
);

CREATE TABLE "sov_campaign" (
  "campaign_id" int PRIMARY KEY,
  "event_type" varchar NOT NULL,
  "solar_system_id" int NOT NULL,
  "defender_alliance_id" int,
  "structure_id" bigint,
  "start_time" timestamp NOT NULL,
  "first_seen" timestamp,
  "last_seen" timestamp,
  "final_attackers_score" decimal,
  "final_defender_score" decimal
);

CREATE TABLE "battle" (
  "battle_id" int PRIMARY KEY,
  "solar_system_id" int NOT NULL,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "battle_date" date NOT NULL,
  "killmails" int,
  "pilots" int NOT NULL,
  "battle_class" varchar NOT NULL
);

CREATE TABLE "game_event" (
  "event_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_date" date NOT NULL,
  "date_precision" varchar NOT NULL,
  "category" varchar NOT NULL,
  "title" varchar NOT NULL,
  "source_id" int NOT NULL,
  "source_ref" varchar
);

CREATE TABLE "source_document" (
  "source_id" int PRIMARY KEY,
  "source_name" varchar NOT NULL,
  "publisher" varchar NOT NULL,
  "url" varchar,
  "retrieved_at" timestamp,
  "sha256" varchar,
  "data_nature" varchar
);

CREATE TABLE "plan" (
  "plan_id" int PRIMARY KEY,
  "plan_name" varchar NOT NULL,
  "product_type" varchar NOT NULL,
  "billing_cycle_months" int
);

CREATE TABLE "plan_price" (
  "plan_id" int,
  "effective_date" date,
  "currency" varchar,
  "list_price" decimal,
  "sale_price" decimal,
  "source_id" int NOT NULL,
  PRIMARY KEY ("plan_id", "effective_date", "currency")
);

CREATE TABLE "market_history_daily" (
  "date" date,
  "region_id" int,
  "type_id" int,
  "average_price" decimal,
  "highest_price" decimal,
  "lowest_price" decimal,
  "volume" bigint,
  "order_count" int,
  PRIMARY KEY ("date", "region_id", "type_id")
);

CREATE TABLE "financial_metric" (
  "metric_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "granularity" varchar NOT NULL,
  "entity" varchar NOT NULL,
  "metric" varchar NOT NULL,
  "geography" varchar,
  "amount" decimal NOT NULL,
  "currency" varchar NOT NULL,
  "source_id" int NOT NULL
);

CREATE TABLE "fx_rate" (
  "date" date,
  "currency_pair" varchar,
  "rate" decimal NOT NULL,
  PRIMARY KEY ("date", "currency_pair")
);

CREATE TABLE "economy_daily" (
  "date" date,
  "metric" varchar,
  "value" decimal NOT NULL,
  PRIMARY KEY ("date", "metric")
);

CREATE TABLE "interest_metric" (
  "period_start" date,
  "granularity" varchar,
  "source" varchar,
  "metric" varchar,
  "geography" varchar,
  "value" decimal NOT NULL,
  "source_id" int NOT NULL,
  PRIMARY KEY ("period_start", "granularity", "source", "metric", "geography")
);

CREATE TABLE "steam_review" (
  "recommendation_id" bigint PRIMARY KEY,
  "steam_author_id" bigint,
  "created_date" date NOT NULL,
  "language" varchar,
  "voted_up" boolean,
  "playtime_at_review_hours" decimal,
  "steam_purchase" boolean,
  "received_for_free" boolean,
  "votes_up" int,
  "review_text" text
);

CREATE TABLE "forum_topic" (
  "topic_id" int PRIMARY KEY,
  "title" varchar NOT NULL,
  "created_date" date NOT NULL,
  "posts_count" int,
  "matched_query" varchar
);

CREATE TABLE "forum_post" (
  "post_id" int PRIMARY KEY,
  "topic_id" int NOT NULL,
  "created_date" date NOT NULL,
  "author_hash" varchar,
  "post_text" text
);

CREATE TABLE "benchmark_metric" (
  "benchmark_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game" varchar NOT NULL,
  "metric" varchar NOT NULL,
  "value" decimal NOT NULL,
  "unit" varchar,
  "period" varchar,
  "source_id" int NOT NULL
);

CREATE INDEX ON "killmail_participant" ("character_id", "killmail_id");

COMMENT ON TABLE "calendar_date" IS 'Generated. The glue between per-player and company-level data.';

COMMENT ON COLUMN "calendar_date"."month" IS 'first day of month, for cohorts and MAU';

COMMENT ON COLUMN "calendar_date"."quarter" IS 'e.g. 2025Q3, joins Pearl Abyss quarters';

COMMENT ON COLUMN "calendar_date"."after_sale" IS 'on or after 2026-05-01, when Pearl Abyss sold CCP';

COMMENT ON TABLE "region" IS 'SDE mapRegions [9].';

COMMENT ON TABLE "constellation" IS 'SDE mapConstellations [9]. Needed for sovereignty campaigns.';

COMMENT ON TABLE "solar_system" IS 'SDE mapSolarSystems [9], security band from MER static_solarsystems [4].';

COMMENT ON COLUMN "solar_system"."security_band" IS 'High Sec / Low Sec / Null Sec / Wormhole';

COMMENT ON TABLE "item_category" IS 'SDE categories [9].';

COMMENT ON COLUMN "item_category"."category_name" IS 'e.g. Ship, Module, Charge';

COMMENT ON TABLE "item_group" IS 'SDE groups [9]. Ship class for feature adoption.';

COMMENT ON COLUMN "item_group"."group_name" IS 'e.g. Frigate, Assault Frigate, Battleship';

COMMENT ON TABLE "item_type" IS 'SDE types [9].';

COMMENT ON COLUMN "item_type"."mean_isk_value" IS 'MER static_type_values [4]';

COMMENT ON COLUMN "item_type"."alpha_can_fly" IS 'ships only: every required skill within the Alpha clone limits (SDE cloneGrades + typeDogma)';

COMMENT ON TABLE "alliance" IS 'Character dump alliances.json [2].';

COMMENT ON TABLE "corporation" IS 'Character dump corporations.json [2].';

COMMENT ON COLUMN "corporation"."is_npc" IS 'corporation_id < 2000000 (CCP-run starter corps, incl. Doomheim)';

COMMENT ON TABLE "player_character" IS 'Customer. Character dump [2] + ESI [2b]. Scope: characters active in killmails or contracts, Jan 2024 - Aug 2026 (889,560). Signup totals for everyone are in character_signup_month.';

COMMENT ON COLUMN "player_character"."character_id" IS 'Customer. One account can own several characters.';

COMMENT ON COLUMN "player_character"."signup_date" IS 'birthday: dump if real (>= 2003), else ESI, else null';

COMMENT ON COLUMN "player_character"."signup_date_source" IS 'dump / esi / unknown';

COMMENT ON COLUMN "player_character"."cohort_month" IS 'first day of signup month';

COMMENT ON COLUMN "player_character"."corporation_id" IS 'current, at snapshot';

COMMENT ON COLUMN "player_character"."is_deleted" IS 'dump deleted flag, ESI 404, or corporation = Doomheim (1000001)';

COMMENT ON COLUMN "player_character"."inferred_plan" IS 'omega (seen in a ship an Alpha cannot fly) / unknown. Never "alpha": absence proves nothing';

COMMENT ON COLUMN "player_character"."first_omega_seen" IS 'first killmail in an Omega-only ship';

COMMENT ON TABLE "character_signup_month" IS 'Exact signups for every character, seen or not, deleted or not [11]. Characters, not accounts.';

COMMENT ON COLUMN "character_signup_month"."first_character_id" IS 'first character created that month';

COMMENT ON COLUMN "character_signup_month"."characters_created" IS 'next month first ID minus this month first ID';

COMMENT ON TABLE "killmail" IS 'UsageEvent. One ship destroyed [1].';

COMMENT ON TABLE "killmail_participant" IS 'Victim and attackers in one table, so "was this character active?" is one lookup [1].';

COMMENT ON COLUMN "killmail_participant"."participant_no" IS '0 = victim, 1..n = attackers';

COMMENT ON COLUMN "killmail_participant"."role" IS 'victim / attacker';

COMMENT ON COLUMN "killmail_participant"."character_id" IS 'null for NPCs and structures';

COMMENT ON COLUMN "killmail_participant"."corporation_id" IS 'at the time of the kill';

COMMENT ON COLUMN "killmail_participant"."alliance_id" IS 'at the time of the kill';

COMMENT ON COLUMN "killmail_participant"."damage" IS 'damage_taken for victim, damage_done for attacker';

COMMENT ON TABLE "contract" IS 'Non-combat activity (traders, haulers). Daily snapshots deduplicated on contract_id [10].';

COMMENT ON COLUMN "contract"."contract_type" IS 'item_exchange / auction / courier';

COMMENT ON COLUMN "contract"."first_seen" IS 'first daily snapshot containing it';

COMMENT ON COLUMN "contract"."last_seen" IS 'last daily snapshot containing it';

COMMENT ON TABLE "character_month_activity" IS 'Derived from killmail_participant and contract. Feeds DAU/MAU, cohort retention, churn, social glue.';

COMMENT ON COLUMN "character_month_activity"."active_days" IS 'days with a killmail or a contract';

COMMENT ON COLUMN "character_month_activity"."in_player_corporation" IS 'last seen in a non-NPC corporation that month';

COMMENT ON TABLE "players_online_daily" IS 'Concurrent players, all activities, from 30-minute points [12].';

COMMENT ON COLUMN "players_online_daily"."outage_minutes" IS 'minutes with no data or 0 players outside daily downtime: service-quality proxy';

COMMENT ON TABLE "war" IS 'Latest daily snapshot of each war [16].';

COMMENT ON TABLE "sov_campaign" IS 'Territory fights. Hourly snapshots deduplicated on campaign_id [17].';

COMMENT ON COLUMN "sov_campaign"."event_type" IS 'e.g. tcu_defense, ihub_defense';

COMMENT ON TABLE "battle" IS 'Derived: killmails in the same system within an hour with 50+ distinct pilots [1].';

COMMENT ON COLUMN "battle"."pilots" IS 'distinct characters involved';

COMMENT ON COLUMN "battle"."battle_class" IS 'skirmish (50-99 pilots) / war (100+ pilots). Size of a fight, not the official war declarations in the war table';

COMMENT ON TABLE "game_event" IS 'Timeline: patch notes and SDE builds [22], news [15], EVE University list [22], lore events [23].';

COMMENT ON COLUMN "game_event"."date_precision" IS 'day / month / year';

COMMENT ON COLUMN "game_event"."category" IS 'expansion / patch / deployment / sale / monetization / company / war / lore';

COMMENT ON COLUMN "game_event"."source_ref" IS 'article slug, SDE build number or video timestamp';

COMMENT ON TABLE "source_document" IS 'data/raw/sources.csv. Provenance for every figure.';

COMMENT ON COLUMN "source_document"."data_nature" IS 'real / anonymised / synthetic';

COMMENT ON TABLE "plan" IS 'Plan. Omega periods from CCP annual accounts [8]; packs from store pages [6] and news [7].';

COMMENT ON COLUMN "plan"."plan_name" IS 'e.g. Omega 1 month, Omega 12 months, PLEX 500';

COMMENT ON COLUMN "plan"."product_type" IS 'subscription / in-game currency';

COMMENT ON COLUMN "plan"."billing_cycle_months" IS '1, 3, 6, 12, 24 (CCP accounting policy)';

COMMENT ON TABLE "plan_price" IS 'Price history [6][7].';

COMMENT ON COLUMN "plan_price"."sale_price" IS 'when a sale was running';

COMMENT ON TABLE "market_history_daily" IS 'Market history [3]. PLEX (type_id 44992) is the monetization signal for 2026.';

COMMENT ON COLUMN "market_history_daily"."average_price" IS 'ISK';

COMMENT ON TABLE "financial_metric" IS 'One reported figure per row. CCP annual accounts and Pearl Abyss reports [8].';

COMMENT ON COLUMN "financial_metric"."granularity" IS 'quarter / year';

COMMENT ON COLUMN "financial_metric"."entity" IS 'CCP ehf. / Pearl Abyss (EVE IP)';

COMMENT ON COLUMN "financial_metric"."metric" IS 'total_revenue, subscription_and_ingame_revenue, marketing_expense, deferred_subscriptions, ...';

COMMENT ON COLUMN "financial_metric"."geography" IS 'North America / Europe / Asia / Other, when reported';

COMMENT ON COLUMN "financial_metric"."currency" IS 'USD (CCP) / KRW (Pearl Abyss)';

COMMENT ON TABLE "fx_rate" IS 'FRED daily exchange rates [13]. Converts Pearl Abyss KRW to USD.';

COMMENT ON COLUMN "fx_rate"."currency_pair" IS 'KRW/USD, USD/EUR';

COMMENT ON TABLE "economy_daily" IS 'MER [4] (latest MER only: each MER holds full history). Also the totals for miners and traders.';

COMMENT ON COLUMN "economy_daily"."metric" IS 'total_isk, character_isk, isk_velocity, sink:<entry>, faucet:<entry>, mined_value, trade_value';

COMMENT ON TABLE "interest_metric" IS 'External interest and channel signals, one figure per row: Google Trends [20], Steam players [14], Twitch [21].';

COMMENT ON COLUMN "interest_metric"."granularity" IS 'week / month / year';

COMMENT ON COLUMN "interest_metric"."source" IS 'google_trends / steam / twitch';

COMMENT ON COLUMN "interest_metric"."metric" IS 'search_interest, avg_players, peak_players, hours_watched, avg_viewers, peak_viewers, streamers';

COMMENT ON COLUMN "interest_metric"."geography" IS 'Worldwide or country (Google Trends by country)';

COMMENT ON TABLE "steam_review" IS 'SurveyResponse proxy. Steam appreviews API, app 8500 [5].';

COMMENT ON COLUMN "steam_review"."steam_author_id" IS 'Steam account, NOT linkable to a character';

COMMENT ON COLUMN "steam_review"."voted_up" IS 'recommend yes / no: the NPS proxy';

COMMENT ON TABLE "forum_topic" IS 'Official forums [18].';

COMMENT ON COLUMN "forum_topic"."matched_query" IS 'search query that found it (title must also be on topic)';

COMMENT ON TABLE "forum_post" IS 'Official forums [18]. Feeds sentiment around price changes and the sale.';

COMMENT ON COLUMN "forum_post"."author_hash" IS 'hashed forum username: counts distinct posters without storing names';

COMMENT ON TABLE "benchmark_metric" IS 'Published MMO figures and figures computed from the WoWAH dataset [19]: the sanity check.';

COMMENT ON COLUMN "benchmark_metric"."game" IS 'World of Warcraft, EverQuest II, AION';

COMMENT ON COLUMN "benchmark_metric"."metric" IS 'e.g. monthly_churn, retention_month_3';

COMMENT ON COLUMN "benchmark_metric"."period" IS 'years the study covers';

ALTER TABLE "constellation" ADD FOREIGN KEY ("region_id") REFERENCES "region" ("region_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "solar_system" ADD FOREIGN KEY ("constellation_id") REFERENCES "constellation" ("constellation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_group" ADD FOREIGN KEY ("category_id") REFERENCES "item_category" ("category_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item_type" ADD FOREIGN KEY ("group_id") REFERENCES "item_group" ("group_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "corporation" ADD FOREIGN KEY ("alliance_id") REFERENCES "alliance" ("alliance_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_character" ADD FOREIGN KEY ("corporation_id") REFERENCES "corporation" ("corporation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail" ADD FOREIGN KEY ("kill_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail" ADD FOREIGN KEY ("solar_system_id") REFERENCES "solar_system" ("solar_system_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail" ADD FOREIGN KEY ("war_id") REFERENCES "war" ("war_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail" ADD FOREIGN KEY ("battle_id") REFERENCES "battle" ("battle_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("killmail_id") REFERENCES "killmail" ("killmail_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("character_id") REFERENCES "player_character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("corporation_id") REFERENCES "corporation" ("corporation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("alliance_id") REFERENCES "alliance" ("alliance_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("ship_type_id") REFERENCES "item_type" ("type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "killmail_participant" ADD FOREIGN KEY ("weapon_type_id") REFERENCES "item_type" ("type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contract" ADD FOREIGN KEY ("issuer_character_id") REFERENCES "player_character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contract" ADD FOREIGN KEY ("issuer_corporation_id") REFERENCES "corporation" ("corporation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contract" ADD FOREIGN KEY ("issued_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contract" ADD FOREIGN KEY ("region_id") REFERENCES "region" ("region_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "contract" ADD FOREIGN KEY ("solar_system_id") REFERENCES "solar_system" ("solar_system_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "character_month_activity" ADD FOREIGN KEY ("character_id") REFERENCES "player_character" ("character_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "players_online_daily" ADD FOREIGN KEY ("date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "war" ADD FOREIGN KEY ("aggressor_corporation_id") REFERENCES "corporation" ("corporation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "war" ADD FOREIGN KEY ("aggressor_alliance_id") REFERENCES "alliance" ("alliance_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "war" ADD FOREIGN KEY ("defender_corporation_id") REFERENCES "corporation" ("corporation_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "war" ADD FOREIGN KEY ("defender_alliance_id") REFERENCES "alliance" ("alliance_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sov_campaign" ADD FOREIGN KEY ("solar_system_id") REFERENCES "solar_system" ("solar_system_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sov_campaign" ADD FOREIGN KEY ("defender_alliance_id") REFERENCES "alliance" ("alliance_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "battle" ADD FOREIGN KEY ("solar_system_id") REFERENCES "solar_system" ("solar_system_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "battle" ADD FOREIGN KEY ("battle_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "game_event" ADD FOREIGN KEY ("event_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "game_event" ADD FOREIGN KEY ("source_id") REFERENCES "source_document" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_price" ADD FOREIGN KEY ("plan_id") REFERENCES "plan" ("plan_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_price" ADD FOREIGN KEY ("effective_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plan_price" ADD FOREIGN KEY ("source_id") REFERENCES "source_document" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "market_history_daily" ADD FOREIGN KEY ("date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "market_history_daily" ADD FOREIGN KEY ("region_id") REFERENCES "region" ("region_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "market_history_daily" ADD FOREIGN KEY ("type_id") REFERENCES "item_type" ("type_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "financial_metric" ADD FOREIGN KEY ("period_start") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "financial_metric" ADD FOREIGN KEY ("source_id") REFERENCES "source_document" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fx_rate" ADD FOREIGN KEY ("date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "economy_daily" ADD FOREIGN KEY ("date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "interest_metric" ADD FOREIGN KEY ("period_start") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "interest_metric" ADD FOREIGN KEY ("source_id") REFERENCES "source_document" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "steam_review" ADD FOREIGN KEY ("created_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forum_topic" ADD FOREIGN KEY ("created_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forum_post" ADD FOREIGN KEY ("topic_id") REFERENCES "forum_topic" ("topic_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "forum_post" ADD FOREIGN KEY ("created_date") REFERENCES "calendar_date" ("date") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "benchmark_metric" ADD FOREIGN KEY ("source_id") REFERENCES "source_document" ("source_id") DEFERRABLE INITIALLY IMMEDIATE;
